# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(default='Nairobi', max_length=70)),
                ('country', models.CharField(default='Kenya', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='Image', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
                ('image_desc', models.CharField(max_length=70)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Location')),
            ],
        ),
    ]
