# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_name',
            field=models.CharField(default='IMG', max_length=30),
        ),
    ]
