# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Category',
            field=models.ManyToManyField(to='photos.Category'),
        ),
    ]
