# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Category',
            new_name='category',
        ),
    ]
